# https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/

services:
  backend:
    image: 'node:16'
    container_name: 'backend'
    hostname: backend

    user: 'node'
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    environment:
      HELLO: 'WORLD'
    ports:
      - 8081:8080
    command: './entry.sh'

  browserless_engine:
    image: 'browserless/chrome'
    container_name: 'browserless_engine'
    hostname: browserless_engine
    
    volumes:
      - ./user-dir/testhelloworld04:/tmp/Default
    # working_dir: /usr/src/app
    environment:
      CONNECTION_TIMEOUT: '15000'
      DEFAULT_IGNORE_HTTPS_ERRORS: 'true'
      MAX_CONCURRENT_SESSIONS: '5'
      MAX_QUEUE_LENGTH: '999'
      FUNCTION_ENABLE_INCOGNITO_MODE: 'true'
      DEFAULT_USER_DATA_DIR: '/tmp/Default'
    ports:
      - 3000:3000
