python-puppeteer-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd python-puppeteer-tryout
          pipenv run python3 ./main.py
        popd

      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v2
      with:
        name: 'upload-artifact-tryout'
        path: python-puppeteer-tryout/*.png
