python-puppeteer-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - run: |
        cd python-puppeteer-tryout/test_pages
          live-server . &
        cd ../..

    - run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        python3 -V
        python3 -m pip install pipenv

        export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
        export PATH="$PATH:$PYTHON_BIN_PATH"

        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

        pipenv --help

    - run: |
        cd python-puppeteer-tryout
          pipenv sync
          pipenv run python3 src/main.py
        cd ..
