FROM logickee/openbox-poe-seat-final

# ARG HELLO=WORLD
# ARG ANDROID_API_LEVEL=25
# ENV HELLO ${ANDROID_API_LEVEL}

COPY ./etc/ /etc/
ADD ./etc/run_supervisord.sh /etc/run_supervisord.sh
RUN chmod +x /etc/run_supervisord.sh

# WORKDIR /root

# NOTE: chrome may fail running root with user-data-dir and --no-sandbox option.
# NOTE: finding out why


# RUN useradd logic
# RUN mkdir -p /home/logic
# WORKDIR /home/logic
# USER 1000:1000

RUN groupadd logic
RUN useradd -u 1000 -g logic \
  -d /home/logic \
  -s /bin/bash -p $(echo blablabla | openssl passwd -1 -stdin) logic
WORKDIR /home/logic

# TODO: remove me
RUN cp /root/.bashrc /home/logic/.bashrc
# RUN touch /home/logic/.bashrc


# # NOTE: corelated to the supervisiord config file
ENV HOME /home/logic

# # NOTE: changing to user will fail vncserver
RUN mkdir -p /home/logic/.vnc
RUN echo 123456 | vncpasswd -f > /home/logic/.vnc/passwd
RUN chmod 600 /home/logic/.vnc/passwd
# # NOTE: vnc setup done

ADD etc/xdg/pcmanfm /home/logic/.config/pcmanfm

RUN chown 1000:1000 -R /home/logic

# init volumes
RUN mkdir /share
RUN chown 1000:1000 -R /share
VOLUME /share

RUN mkdir /logs
RUN chown 1000:1000 -R /logs
VOLUME /logs

RUN mkdir /node_modules
RUN chown 1000:1000 -R /node_modules
VOLUME /node_modules

RUN mkdir -p /workspace/firefox-user-data
RUN chown 1000:1000 -R /workspace/firefox-user-data
VOLUME /workspace/firefox-user-data

RUN mkdir -p /workspace/chrome-user-data
RUN chown 1000:1000 -R /workspace/chrome-user-data
VOLUME /workspace/chrome-user-data


RUN mkdir -p /installed &&  touch /installed/final_done

USER 1000

CMD ["/etc/run_supervisord.sh"]
